from .longtake_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .facerefine_node import NODE_CLASS_MAPPINGS as _FR_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as _FR_NAMES
from .metadata_nodes import NODE_CLASS_MAPPINGS as _MD_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as _MD_NAMES

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **_FR_CLASSES, **_MD_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **_FR_NAMES, **_MD_NAMES}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
